# Generated by Django 2.1.7 on 2019-03-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
