# Generated by Django 2.1.7 on 2019-03-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixr', '0002_playlist_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='spotify_playlist_id',
            field=models.CharField(max_length=40),
        ),
    ]
