# Generated by Django 2.1.7 on 2019-03-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixr', '0003_auto_20190304_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='spotify_playlist_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
