# Generated by Django 2.1.7 on 2019-04-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixr', '0004_auto_20190305_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='user_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
