# Generated by Django 2.1.7 on 2019-04-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixr', '0007_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='playlist',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
