# Generated by Django 2.1.7 on 2019-04-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixr', '0009_auto_20190430_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='prof_username',
            field=models.CharField(default='cbass25', max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
