# Generated by Django 2.1.7 on 2019-05-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixr', '0011_auto_20190430_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
